services:
  postgres_test:
    image: postgres:16-alpine
    container_name: avito_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 20
    networks:
      - avito_network

  api_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_api_test
    environment:
      DB_URL: postgres://postgres:postgres@postgres_test:5432/test_db?sslmode=disable
      SERVE_PORT: 8080
      SHUTDOWN_TIMEOUT: 5
      ADMIN_TOKEN: admin-token-test
    ports:
      - "8081:8080"
    depends_on:
      postgres_test:
        condition: service_healthy
    networks:
      - avito_network

networks:
  avito_network:
    driver: bridge